[package]
name = "smithay-egui"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
cgmath = "0.18"
egui = "0.16"
memoffset = "0.6"
lazy_static = { version = "1.4.0", optional = true }
slog = { version = "2.7.0", optional = true }
xkbcommon = "0.4"

[dependencies.smithay]
version = "0.3"
git = "https://github.com/Smithay/smithay.git"
rev = "8558253b"
default-features = false
features = ["renderer_gl", "wayland_frontend"]

[features]
default = ["default_fonts", "render_element"]
# Let egui bundle some fonts by default.
default_fonts = ["egui/default_fonts"]
render_element = ["smithay/desktop", "lazy_static", "slog"]

[dev-dependencies]
anyhow = "1.0"
egui_demo_lib = "0.16"
slog = "2.7"
slog-term = "2.8"
slog-scope = "4.4"
slog-stdlog = "4.1"

[dev-dependencies.smithay]
version = "0.3"
git = "https://github.com/Smithay/smithay.git"
rev = "8558253b"
default-features = false
features = ["renderer_gl", "backend_winit", "slog-stdlog"]